name: full Docker Image CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker container Master
      run: docker build . --file Dockerfile_master --tag my-image-name:$(date +%s)
    - name: Build Docker container node
      run: docker build . --file Dockerfile_node --tag my-image-name:$(date +%s)
      
    - name: Test dependency script Master
      run: ./dependencies_MasterHost.sh
    - name: Test dependency script node
      run: ./dependencies_NodesHost.sh
      
