name: full Docker Image CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker container Master
      run: docker build . --file Master/Dockerfile --tag ubuntuofclustermaster:20.04
    - name: Build Docker container node
      run: docker build . --file Node/Dockerfile --tag ubuntuofclusternode:20.04
